production:
  adapter: postgresql
  database: redmine_db
  host: db
  username: redmine
  password: redmine_password
  encoding: utf8

development:
  adapter: postgresql
  database: redmine_db
  host: db
  username: redmine
  password: redmine_password
  encoding: utf8
