services:
  redmine:
    image: redmine:5
    ports:
      - "9090:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./config/database.yml:/usr/src/redmine/config/database.yml

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redmine-files:
  redmine-plugins:
  postgres-data:
