services:
  redmine:
    image: redmine:5-alpine
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine_db
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - /workspaces/contact_form_redmine_V1/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - /workspaces/contact_form_redmine_V1/config/database.yml:/usr/src/redmine/config/database.yml
    depends_on:
      - db

  email-receiver:
    image: redmine:5-alpine
    command: bash -c "while true; do rake redmine:email:receive_imap RAILS_ENV=production host=imap.gmail.com username=testgabriel44@gmail.com password='yfwy ykxq bwcs dtlu' port=993 ssl=true allow_override=project,priority project=support tracker=Support; sleep 60; done"
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - /workspaces/contact_form_redmine_V1/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - /workspaces/contact_form_redmine_V1/config/database.yml:/usr/src/redmine/config/database.yml
    depends_on:
      - redmine
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redmine-files:
  redmine-plugins:
  postgres-data: