services:
  redmine:
    image: redmine:5
    ports:
      - "9090:3000"  # Changed to use port 9090
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./config/database.yml:/usr/src/redmine/config/database.yml
    depends_on:
      - db

  email-receiver:
    image: redmine:5
    command: bash -c "
      sleep 30 &&
      cd /usr/src/redmine &&
      echo 'Starting email receiver service...' &&
      while true; do
        echo '[`date`] Checking for new emails...' &&
        bundle exec rake redmine:email:receive_imap RAILS_ENV=production \
          host=imap.gmail.com \
          username=testgabriel44@gmail.com \
          password='yfwy ykxq bwcs dtlu' \
          port=993 \
          ssl=true \
          allow_override=project,priority \
          project=support \
          tracker=Support \
          verbose=1 2>&1 &&
        sleep 60
      done"
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./config/database.yml:/usr/src/redmine/config/database.yml
    depends_on:
      - redmine
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redmine-files:
  redmine-plugins:
  postgres-data:
