services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redmine:
    image: redmine:5-alpine
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine_db
      RAILS_ENV: production
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
      - ./config/database.yml:/usr/src/redmine/config/database.yml:ro
    depends_on:
      - db
    restart: unless-stopped
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for PostgreSQL to start...'
          sleep 2
        done
        echo 'PostgreSQL is up - starting Redmine'
        bundle exec rails server -b 0.0.0.0
      "

  email-receiver:
    image: redmine:5-alpine
    entrypoint: ["/bin/sh", "-c"]
    command: |
      apk add --no-cache netcat-openbsd &&
      while ! nc -z redmine 3000; do
        echo "Waiting for Redmine to be ready..."
        sleep 5
      done
      while true; do
        echo "[$(date)] Starting email check..."
        rake redmine:email:receive_imap RAILS_ENV=production \
          host=imap.gmail.com \
          username=testgabriel44@gmail.com \
          password='yfwy ykxq bwcs dtlu' \
          port=993 \
          ssl=true \
          allow_override=project,priority \
          project=support \
          tracker=Support 2>&1 || echo "Email check failed"
        echo "[$(date)] Waiting 60 seconds before next check..."
        sleep 60
      done
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml:ro
      - ./config/database.yml:/usr/src/redmine/config/database.yml:ro
    depends_on:
      - redmine
    restart: unless-stopped

volumes:
  redmine-files:
  redmine-plugins:
  postgres-data:
