services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redmine:
    image: redmine:5-alpine
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine_db
    volumes:
      - redmine-files:/usr/src/redmine/files
      - ./config:/usr/src/redmine/config:ro
    depends_on:
      - db

  email-receiver:
    image: redmine:5-alpine
    command: >
      sh -c "
        sleep 30 &&
        while true; do
          rake redmine:email:receive_imap RAILS_ENV=production host=imap.gmail.com username=testgabriel44@gmail.com password='yfwy ykxq bwcs dtlu' port=993 ssl=true project=support tracker=Support || true;
          sleep 60;
        done"
    volumes:
      - redmine-files:/usr/src/redmine/files
      - ./config:/usr/src/redmine/config:ro
    depends_on:
      - redmine

volumes:
  redmine-files:
  postgres-data:
