services:
  redmine:
    image: redmine:5-alpine
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine_db
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./config/database.yml:/usr/src/redmine/config/database.yml
    depends_on:
      - db
    restart: unless-stopped
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  email-receiver:
    image: redmine:5-alpine
    entrypoint: ["/bin/sh", "-c"]
    command: |
      while true; do
        echo "[$(date)] Starting email check..."
        rake redmine:email:receive_imap RAILS_ENV=production \
          host=imap.gmail.com \
          username=testgabriel44@gmail.com \
          password='yfwy ykxq bwcs dtlu' \
          port=993 \
          ssl=true \
          allow_override=project,priority \
          project=support \
          tracker=Support || echo "Email check failed"
        echo "[$(date)] Waiting 60 seconds before next check..."
        sleep 60
      done
    volumes:
      - redmine-files:/usr/src/redmine/files
      - redmine-plugins:/usr/src/redmine/plugins
      - ./config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./config/database.yml:/usr/src/redmine/config/database.yml
    depends_on:
      - redmine
      - db
    restart: unless-stopped
    mem_limit: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: redmine_password
      POSTGRES_USER: redmine
      POSTGRES_DB: redmine_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    mem_limit: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redmine-files:
  redmine-plugins:
  postgres-data:
