default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "smtp.gmail.com"
      port: 587
      authentication: :plain
      domain: "gmail.com"
      user_name: "testgabriel44@gmail.com"
      password: "yfwy ykxq bwcs dtlu"
      enable_starttls: true
      openssl_verify_mode: "none"
      tls: false
      ssl: false
  
  # E-Mail-Empfang Konfiguration
  mail_handler:
    enabled: true
    unknown_user: create
    default_group: users
    project_from_subaddress: true
    project: support
    tracker: Support
    category: Email
    priority: Normal
    allow_override: project,tracker,priority,category

production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "smtp.gmail.com"
      port: 587
      authentication: :plain
      domain: "gmail.com"
      user_name: "testgabriel44@gmail.com"
      password: "yfwy ykxq bwcs dtlu"
      enable_starttls: true
      openssl_verify_mode: "none"
      tls: false
      ssl: false
  
  # E-Mail-Empfang Konfiguration
  mail_handler:
    enabled: true
    unknown_user: create
    default_group: users
    project_from_subaddress: true
    project: support
    tracker: Support
    category: Email
    priority: Normal
    allow_override: project,tracker,priority,category
